### ISSUE TITLE
Consider namespacing the examples dotnet tool

### ISSUE THREAD

**Issue by ericsampson** [spectreconsole/errata#1]
It would be nice to namespace the dotnet tool examples like `dotnet-errata-examples` to prevent possible collisions and make it clearer what it is (without having to look at the description field). Cheers!!

**Comment by patriksvensson** [comment]
@ericsampson Not sure I understand what you mean to be honest. Could you elaborate?

**Comment by ericsampson** [comment]
Right now, from your example on Twitter, it seems like it get installed as `dotnet-examples`, which is very generic/doesn't indicate the actual contents, and could potentially have a name clash in the future if Microsoft decides to do something similar.

Does that make sense?

**Comment by patriksvensson** [comment]
Ah. Dotnet Example is a generic tool for examples and has nothing to do with Spectre.Console. 

https://github.com/patriksvensson/dotnet-example

**Comment by ericsampson** [comment]
Ah ok thanks!
